// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGx0cS3Qrwt8OTutNXIdHcnLTYhqNS3ko',
    appId: '1:363069279026:android:149aa28ddfe6a0fb86a52b',
    messagingSenderId: '363069279026',
    projectId: 'ta-ews-rizem-mahendra',
    databaseURL: 'https://ta-ews-rizem-mahendra-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-ews-rizem-mahendra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuKPakGdDsz9W0zcGk7qux5t7jJuiY9Ik',
    appId: '1:363069279026:ios:c048ea73b859e8af86a52b',
    messagingSenderId: '363069279026',
    projectId: 'ta-ews-rizem-mahendra',
    databaseURL: 'https://ta-ews-rizem-mahendra-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-ews-rizem-mahendra.appspot.com',
    iosBundleId: 'com.example.taEwsApplication',
  );
}
